server:
  port: 8080

spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mariadb://localhost:3306/test?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: qwer
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123!@#

token:
  secret:
    key: SpringBootJWTHelperTokenSecretKeyValue123!@#
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12
